services:
  data-preprocessing:
    build: .
    image: data-preprocessing:v1.0.2
    container_name: data-preprocessing
    ports:
      - '1717:1717'
    volumes:
      - ./local-db:/app/local-db
    restart: unless-stopped
